### ISSUE TITLE
Double check description of 30d purge schedule in readme

### ISSUE THREAD

**Issue by greggles** [AppliedTrust/amibackup#1]
This tool looks cool, thanks for open sourcing it :+1: 

```
...  -p 30d:90d:180d   .... 1/mo forever.
```

That looks to me like the "1/mo" will be kept for the past 180 days. It seems good to show a "forever" retention period in case people want that.

**Comment by nmcclain** [comment]
This tool will only purge AMIs within a defined purge window, so in that example, the tool will ignore any AMIs older than 180 days.  Another way of saying it is, if there are no purge windows defined, the tool will never purge anything.

This has been a source of confusion for multiple people, so there is indeed something that needs to be fixed here - I'm very open to suggestions on improving the documentation (or the tool itself!).

**Comment by greggles** [comment]
AHA!

Maybe this merging of your comment into the current README:
```AMIs within Purge Windows are purged. If a time period is not specified then all snapshots that match that time period will be retained."

One more thought, if someone specifies: `-p 30d:90d:180d` does that have the same impact as `-p 30d:90d:150d`?  

Maybe having a few more examples would be the best way to explain the behavior.

**Comment by nmcclain** [comment]
I took a stab at improving the README.

> One more thought, if someone specifies: -p 30d:90d:180d does that have the same impact as -p 30d:90d:150d?
> Assuming that config was in place from day one, then "-p 30d:90d:180d" is functionally identical to "-p 30d:90d:150d".  The corner case where there is a difference is if you have, for example, 10 backups that are 165 days old because you were using a different configuration at some point.  In that case, the latter would purge those extras, whereas the former would ignore them.

Thanks for your feedback on this.  I struggled with the best way to represent this concept on the command line.
